### ISSUE TITLE
Why i get the issue when i complete my login

### ISSUE THREAD

**Issue by Gaurabp** [LinxHQ/linxbooks#33]
CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'admin'@'localhost' (using password: YES)
#0 | +  F:\xampp\htdocs\billing software\linxbooks\framework\db\CDbConnection.php(330): CDbConnection->open()
-- | --
#1 | +  F:\xampp\htdocs\billing software\linxbooks\framework\db\CDbConnection.php(308): CDbConnection->setActive(true)
#2 | +  F:\xampp\htdocs\billing software\linxbooks\framework\base\CModule.php(387): CDbConnection->init()
#3 | +  F:\xampp\htdocs\billing software\linxbooks\framework\base\CApplication.php(450): CModule->getComponent("db")
#4 | +  F:\xampp\htdocs\billing software\linxbooks\framework\db\ar\CActiveRecord.php(634): CApplication->getDb()
#5 | +  F:\xampp\htdocs\billing software\linxbooks\framework\db\ar\CActiveRecord.php(667): CActiveRecord->getDbConnection()
#6 | +  F:\xampp\htdocs\billing software\linxbooks\framework\db\ar\CActiveRecord.php(1455): CActiveRecord->getCommandBuilder()
#7 | –  F:\xampp\htdocs\billing software\linxbooks\protected\components\UserIdentity.php(15): CActiveRecord->find("LOWER(account_email)=?", array("admin"))10     private $_id; 11   12     public function authenticate() 13     { 14         $username = strtolower($this->username); 15         $user = Account::model()->find('LOWER(account_email)=?',array($username)); 16          17         if($user === null) 18             $this->errorCode = self::ERROR_USERNAME_INVALID; 19         else if(!$user->validatePassword($this->password)) 20             $this->errorCode = self::ERROR_PASSWORD_INVALID;
#8 | –  F:\xampp\htdocs\billing software\linxbooks\protected\models\LoginForm.php(55): UserIdentity->authenticate()50     public function authenticate($attribute,$params) 51     { 52         if(!$this->hasErrors()) 53         { 54             $this->_identity=new UserIdentity($this->username,$this->password); 55             if(!$this->_identity->authenticate()) 56                 $this->addError('error','Incorrect username or password.'); 57         } 58     } 59  60     /**
#9 | +  F:\xampp\htdocs\billing software\linxbooks\framework\validators\CInlineValidator.php(42): LoginForm->authenticate("password", array())
#10 | +  F:\xampp\htdocs\billing software\linxbooks\framework\validators\CValidator.php(213): CInlineValidator->validateAttribute(LoginForm, "password")
#11 | +  F:\xampp\htdocs\billing software\linxbooks\framework\base\CModel.php(159): CValidator->validate(LoginForm, array("password"))
#12 | –  F:\xampp\htdocs\billing software\linxbooks\protected\controllers\SiteController.php(174): CModel->validate()169             $model->username=$_POST['LoginForm']['username']; 170                         $model->password=$_POST['LoginForm']['password']; 171                         $model->rememberMe=1; 172 //                        print_r($_POST['LoginForm']); 173             // validate user input and redirect to the previous page if valid 174             if($model->validate() && $model->login()) 175                 $this->redirect(array('/'.LBApplication::getCurrentlySelectedSubscription() . "/lbInvoice/dashboard")); 176                 //$this->redirect(array("project/index")); 177                     // display the login form 178                         //LBApplication::renderPartial($this, 'login', array('model'=>$model)); 179         }
#13 | +  F:\xampp\htdocs\billing software\linxbooks\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#14 | +  F:\xampp\htdocs\billing software\linxbooks\framework\web\CController.php(308): CInlineAction->runWithParams(array())
#15 | +  F:\xampp\htdocs\billing software\linxbooks\framework\web\CController.php(286): CController->runAction(CInlineAction)
#16 | +  F:\xampp\htdocs\billing software\linxbooks\framework\web\CController.php(265): CController->runActionWithFilters(CInlineAction, array())
#17 | +  F:\xampp\htdocs\billing software\linxbooks\framework\web\CWebApplication.php(282): CController->run("login")
#18 | +  F:\xampp\htdocs\billing software\linxbooks\framework\web\CWebApplication.php(141): CWebApplication->runController("")
#19 | +  F:\xampp\htdocs\billing software\linxbooks\framework\base\CApplication.php(180): CWebApplication->processRequest()
#20 | +  F:\xampp\htdocs\billing software\linxbooks\index.php(43): CApplication->run()

**Comment by tuchido** [comment]
Hi Gaurabp,

Hope this guide can help you.

- Create a Mysql database for your installation
- Import the following sql into the database: `sql/setup.sql`. Please make sure your MySQL allows case-insensitive table names. Otherwise you'll get error when reading yiisession table.
- DB info can be edited at `protected/config/db.php`.
- You can then use this account to login to the system.
Username is `admin`, pass is `admin123`
